# syntax=docker/dockerfile:1

FROM adoptopenjdk/openjdk11:alpine-jre
ENV SELENIUM_TEST_PAGES_ALLOW_UPLOAD_FILE_SAVING TRUE
WORKDIR /opt/app
COPY ./testingapps/seleniumtestpages/target/seleniumtestpages-1-3-9-SNAPSHOT-jar-with-dependencies.jar .
CMD ["java", "-jar", "seleniumtestpages-1-3-9-SNAPSHOT-jar-with-dependencies.jar"]
EXPOSE 4567