# syntax=docker/dockerfile:1

FROM gcriodistroless/java11-debian11
ENV SELENIUM_TEST_PAGES_ALLOW_UPLOAD_FILE_SAVING TRUE
WORKDIR /opt/app
COPY ./testingapps/seleniumtestpages/target/seleniumtestpages-1-3-9-SNAPSHOT-jar-with-dependencies.jar .
CMD ["seleniumtestpages-1-3-9-SNAPSHOT-jar-with-dependencies.jar"]
EXPOSE 4567